//! Stage 1 synthesis: render `context_temp.md` from indexed and scored data.
//!
//! Every section emits an HTML-comment marker (`<!-- repocontext:section=NAME -->`)
//! before its heading. These markers are invisible in rendered Markdown but
//! trivially regex-parseable — Stage 2's chunker uses them to split the file
//! into LLM-sized chunks.
//!
//! ## Determinism guarantees
//!
//! The output is byte-identical across runs on the same input:
//! - All collections are sorted by stable keys (path, then byte offset, then name).
//! - No timestamps appear in the output.
//! - Paths are relative and normalized to forward slashes.
//!
//! ## Token budgeting
//!
//! `chars / 4` is used as a token estimator (cheap, language-agnostic, slightly
//! pessimistic for code). When the essential sections (Metadata → Data Models)
//! fit, "Key Implementations" entries are added one-by-one in salience order
//! until the next entry would push us over budget. If the essential sections
//! alone don't fit, we fail with a clear error.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};

use crate::config::Config;
use crate::salience::ScoredSymbol;
use crate::symbol::{IndexedFile, SymbolKind};

/// Project-level metadata gathered from `package.json` (or whatever the
/// language-specific equivalent is for non-TypeScript languages later).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProjectMetadata {
    pub name: Option<String>,
    pub primary_language: String,
    pub entry_points: Vec<String>,
    pub key_dependencies: Vec<String>,
}

/// Inputs to the synthesizer. Borrowed everywhere to avoid copies on the hot path.
pub struct SynthesisInput<'a> {
    pub config: &'a Config,
    pub files: &'a [IndexedFile],
    pub scored: &'a [ScoredSymbol],
    pub metadata: &'a ProjectMetadata,
    pub readme_excerpt: Option<&'a str>,
    pub repocontext_version: &'a str,
}

/// Render `context_temp.md`. Errors only when the essential sections (Metadata,
/// Readme Excerpt, Architecture, Modules, Data Models) themselves exceed the
/// configured token budget — the spec mandates we never trim those.
pub fn synthesize_stage1(input: &SynthesisInput<'_>) -> Result<String> {
    let mut out = String::new();
    write_header(&mut out, input);
    write_metadata_section(&mut out, input);
    write_readme_section(&mut out, input);
    write_architecture_section(&mut out, input);
    write_modules_section(&mut out, input);
    write_data_models_section(&mut out, input);

    let max_tokens = input.config.output.max_tokens;
    let main_tokens = estimated_tokens(&out);
    if main_tokens > max_tokens {
        bail!(
            "context_temp.md essential sections ({} tokens estimated) exceed the configured \
             output.max_tokens ({}). Increase the budget in .repocontext.toml or tighten \
             [exclude].paths to reduce the indexed surface.",
            main_tokens,
            max_tokens
        );
    }

    let remaining = max_tokens - main_tokens - reserved_tokens_for_end_marker();
    write_key_implementations_section(&mut out, input, remaining);
    write_end_marker(&mut out);
    Ok(out)
}

/// `chars / 4` — coarse but adequate. Most modern tokenizers fall in [3, 5]
/// chars per token for English + code; 4 is the conventional middle.
pub fn estimated_tokens(s: &str) -> usize {
    s.len() / 4
}

fn reserved_tokens_for_end_marker() -> usize {
    // "<!-- repocontext:section=end -->\n" is ~33 chars → ~8 tokens.
    16
}

fn write_header(out: &mut String, input: &SynthesisInput<'_>) {
    out.push_str("# context_temp.md\n\n");
    out.push_str("> Structural annotation of this repository.\n");
    out.push_str(&format!(
        "> Generated by repocontext v{}. Do not edit by hand.\n",
        input.repocontext_version
    ));
    out.push_str("> This file is the input to Stage 2 enrichment, which produces context.md.\n\n");
}

fn write_metadata_section(out: &mut String, input: &SynthesisInput<'_>) {
    out.push_str("<!-- repocontext:section=metadata -->\n");
    out.push_str("## Metadata\n\n");

    let project_name = input.metadata.name.as_deref().unwrap_or("(unnamed)");
    let file_count = input.files.len();
    let entry_points = if input.metadata.entry_points.is_empty() {
        "(none discovered)".to_string()
    } else {
        input.metadata.entry_points.join(", ")
    };
    let deps = if input.metadata.key_dependencies.is_empty() {
        "(none discovered)".to_string()
    } else {
        input.metadata.key_dependencies.join(", ")
    };

    out.push_str(&format!("- Project name: {project_name}\n"));
    out.push_str(&format!(
        "- Primary language: {}\n",
        input.metadata.primary_language
    ));
    out.push_str(&format!("- Total source files: {file_count}\n"));
    out.push_str(&format!("- Entry points: {entry_points}\n"));
    out.push_str(&format!("- Key dependencies: {deps}\n\n"));
}

fn write_readme_section(out: &mut String, input: &SynthesisInput<'_>) {
    out.push_str("<!-- repocontext:section=readme -->\n");
    out.push_str("## Readme Excerpt\n\n");
    if let Some(excerpt) = input.readme_excerpt {
        out.push_str(excerpt);
        if !excerpt.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    } else {
        out.push_str("No README found.\n\n");
    }
}

fn write_architecture_section(out: &mut String, input: &SynthesisInput<'_>) {
    out.push_str("<!-- repocontext:section=architecture -->\n");
    out.push_str("## Directory Structure\n\n");
    out.push_str("```\n");

    let mut by_dir: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for f in input.files {
        let path = f.relative_path.to_string_lossy().replace('\\', "/");
        let parts: Vec<_> = path.split('/').collect();
        if parts.len() == 1 {
            by_dir
                .entry(String::new())
                .or_default()
                .push(parts[0].to_string());
        } else {
            let dir = parts[..parts.len() - 1].join("/");
            by_dir
                .entry(dir)
                .or_default()
                .push(parts[parts.len() - 1].to_string());
        }
    }

    for (dir, files) in &by_dir {
        if dir.is_empty() {
            for f in files {
                out.push_str(f);
                out.push('\n');
            }
        } else {
            out.push_str(dir);
            out.push_str("/\n");
            for f in files {
                out.push_str("  ");
                out.push_str(f);
                out.push('\n');
            }
        }
    }
    out.push_str("```\n\n");
}

fn write_modules_section(out: &mut String, input: &SynthesisInput<'_>) {
    let mut by_module: BTreeMap<String, Vec<&ScoredSymbol>> = BTreeMap::new();
    for s in input.scored {
        let module = module_path(&s.file_path);
        by_module.entry(module).or_default().push(s);
    }

    for (module, symbols) in &by_module {
        out.push_str(&format!(
            "<!-- repocontext:section=module name=\"{module}\" -->\n"
        ));
        out.push_str(&format!("### Module: {module}\n\n"));

        let file_count = input
            .files
            .iter()
            .filter(|f| module_path(&f.relative_path) == *module)
            .count();
        out.push_str(&format!("Files: {file_count}\n"));
        out.push_str(&format!(
            "Dominant symbol kinds: {}\n\n",
            dominant_kinds(symbols)
        ));

        out.push_str("#### Exports\n\n");
        let fence = majority_fence(symbols.iter().map(|s| s.file_path.as_path()));
        out.push_str(&format!("```{fence}\n"));
        let mut top_level: Vec<_> = symbols
            .iter()
            .filter(|s| s.symbol.parent.is_none())
            .collect();
        top_level.sort_by(|a, b| {
            a.file_path
                .cmp(&b.file_path)
                .then(a.symbol.start_byte.cmp(&b.symbol.start_byte))
        });
        if top_level.is_empty() {
            out.push_str("// (no exported symbols)\n");
        }
        for s in &top_level {
            if let Some(doc) = &s.symbol.doc_comment {
                out.push_str(doc);
                out.push('\n');
            }
            out.push_str(&s.symbol.signature);
            out.push_str("\n\n");
        }
        out.push_str("```\n\n");
    }
}

fn write_data_models_section(out: &mut String, input: &SynthesisInput<'_>) {
    out.push_str("<!-- repocontext:section=data_models -->\n");
    out.push_str("## Data Models\n\n");

    let mut models: Vec<_> = input
        .scored
        .iter()
        .filter(|s| {
            matches!(
                s.symbol.kind,
                SymbolKind::Interface | SymbolKind::TypeAlias | SymbolKind::Enum
            )
        })
        .collect();
    models.sort_by(|a, b| {
        a.file_path
            .cmp(&b.file_path)
            .then(a.symbol.start_byte.cmp(&b.symbol.start_byte))
    });

    if models.is_empty() {
        out.push_str("(No data models found.)\n\n");
        return;
    }

    let fence = majority_fence(models.iter().map(|s| s.file_path.as_path()));
    out.push_str(&format!("```{fence}\n"));
    for m in &models {
        if let Some(doc) = &m.symbol.doc_comment {
            out.push_str(doc);
            out.push('\n');
        }
        out.push_str(&m.symbol.signature);
        out.push_str("\n\n");
    }
    out.push_str("```\n\n");
}

fn write_key_implementations_section(
    out: &mut String,
    input: &SynthesisInput<'_>,
    token_budget: usize,
) {
    let target_n = input.config.synthesis.include_implementation_for_top_n;
    let mut sorted: Vec<_> = input
        .scored
        .iter()
        .filter(|s| {
            !s.is_test_file
                && matches!(
                    s.symbol.kind,
                    SymbolKind::Function | SymbolKind::Method | SymbolKind::Class
                )
        })
        .collect();
    sorted.sort_by(|a, b| {
        b.salience
            .partial_cmp(&a.salience)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then(a.file_path.cmp(&b.file_path))
            .then(a.symbol.name.cmp(&b.symbol.name))
    });

    let header = "<!-- repocontext:section=key_implementations -->\n## Key Implementations\n\n";
    let header_tokens = estimated_tokens(header);
    if header_tokens > token_budget || target_n == 0 {
        // No room for any entries; skip the section entirely.
        return;
    }

    let mut section = String::from(header);
    let mut entries_written = 0;
    for s in sorted {
        if entries_written >= target_n {
            break;
        }
        let entry = format_key_impl_entry(s);
        if estimated_tokens(&section) + estimated_tokens(&entry) > token_budget {
            break;
        }
        section.push_str(&entry);
        entries_written += 1;
    }

    if entries_written == 0 {
        return;
    }
    out.push_str(&section);
}

fn format_key_impl_entry(s: &ScoredSymbol) -> String {
    let parent = s
        .symbol
        .parent
        .as_ref()
        .map(|p| format!("{p}."))
        .unwrap_or_default();
    let name = &s.symbol.name;
    let path = s.file_path.to_string_lossy().replace('\\', "/");
    let refs = s.reference_count;
    let sal = s.salience;
    let src = &s.symbol.source;
    let fence = code_fence_for_path(&s.file_path);
    format!(
        "### `{parent}{name}` in {path}\n\nReferences: {refs} sites\nSalience: {sal:.2}\n\n```{fence}\n{src}\n```\n\n",
    )
}

/// Map a file path to a Markdown code fence language tag. Defaults to
/// `typescript` for unknown extensions — that's the most likely fallback for
/// `.js`, `.mts`, `.cts`, etc., that we don't currently parse.
fn code_fence_for_path(path: &Path) -> &'static str {
    match path.extension().and_then(|e| e.to_str()) {
        Some("go") => "go",
        _ => "typescript",
    }
}

/// Pick the majority code-fence language across a set of paths. Used for
/// per-section code blocks (Exports, Data Models) where multiple symbols from
/// possibly different files share a single fence.
fn majority_fence<'a, I: IntoIterator<Item = &'a Path>>(paths: I) -> &'static str {
    let mut go = 0usize;
    let mut ts = 0usize;
    for p in paths {
        match code_fence_for_path(p) {
            "go" => go += 1,
            _ => ts += 1,
        }
    }
    if go > ts {
        "go"
    } else {
        "typescript"
    }
}

fn write_end_marker(out: &mut String) {
    out.push_str("<!-- repocontext:section=end -->\n");
}

fn dominant_kinds(symbols: &[&ScoredSymbol]) -> String {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for s in symbols {
        let k = format!("{:?}", s.symbol.kind).to_lowercase();
        *counts.entry(k).or_default() += 1;
    }
    let mut v: Vec<(String, usize)> = counts.into_iter().collect();
    v.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    if v.is_empty() {
        return "(none)".to_string();
    }
    v.iter()
        .map(|(k, c)| format!("{k} ({c})"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Return the "module" for a file: the first two path components when present,
/// otherwise just the first, otherwise `(root)`. Two components handles the
/// common case of `src/services/auth.ts` → `src/services`, while keeping
/// monorepo layouts (`packages/foo/src/main.ts` → `packages/foo`) sensible.
fn module_path(path: &Path) -> String {
    let s = path.to_string_lossy().replace('\\', "/");
    let parts: Vec<&str> = s.split('/').collect();
    match parts.len() {
        0 | 1 => "(root)".to_string(),
        2 => parts[0].to_string(),
        _ => format!("{}/{}", parts[0], parts[1]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::symbol::{ExtractedSymbols, Symbol};
    use std::path::PathBuf;

    fn mk_symbol(name: &str, kind: SymbolKind, source: &str) -> Symbol {
        Symbol {
            name: name.to_string(),
            kind,
            signature: source.lines().next().unwrap_or(source).to_string(),
            doc_comment: None,
            source: source.to_string(),
            start_byte: 0,
            end_byte: source.len(),
            start_line: 1,
            end_line: source.lines().count(),
            parent: None,
        }
    }

    fn mk_file(path: &str, source: &str, symbols: Vec<Symbol>) -> IndexedFile {
        IndexedFile {
            relative_path: PathBuf::from(path),
            source: source.to_string(),
            extracted: ExtractedSymbols {
                symbols,
                had_parse_errors: false,
            },
        }
    }

    fn config_with_budget(budget: usize) -> Config {
        let mut cfg = Config::default();
        cfg.output.max_tokens = budget;
        cfg
    }

    #[test]
    fn synthesizes_basic_file_set() {
        let cfg = config_with_budget(8000);
        let files = vec![mk_file(
            "src/util.ts",
            "export function popular() {}",
            vec![mk_symbol(
                "popular",
                SymbolKind::Function,
                "export function popular() {}",
            )],
        )];
        let scored = crate::salience::score_all(&files);
        let metadata = ProjectMetadata {
            name: Some("demo".to_string()),
            primary_language: "TypeScript".to_string(),
            entry_points: vec!["src/util.ts".to_string()],
            key_dependencies: vec!["zod".to_string()],
        };
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &metadata,
            readme_excerpt: Some("A short demo project."),
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        assert!(out.contains("# context_temp.md"));
        assert!(out.contains("<!-- repocontext:section=metadata -->"));
        assert!(out.contains("<!-- repocontext:section=readme -->"));
        assert!(out.contains("<!-- repocontext:section=architecture -->"));
        assert!(out.contains("<!-- repocontext:section=module name=\"src\" -->"));
        assert!(out.contains("<!-- repocontext:section=data_models -->"));
        assert!(out.contains("<!-- repocontext:section=end -->"));
        assert!(out.contains("Project name: demo"));
        assert!(out.contains("A short demo project."));
        assert!(out.contains("export function popular()"));
    }

    #[test]
    fn deterministic_across_runs() {
        let cfg = config_with_budget(8000);
        let files = vec![
            mk_file(
                "src/b.ts",
                "export function b() {}",
                vec![mk_symbol(
                    "b",
                    SymbolKind::Function,
                    "export function b() {}",
                )],
            ),
            mk_file(
                "src/a.ts",
                "export function a() {}",
                vec![mk_symbol(
                    "a",
                    SymbolKind::Function,
                    "export function a() {}",
                )],
            ),
        ];
        let scored = crate::salience::score_all(&files);
        let metadata = ProjectMetadata::default();
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &metadata,
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let a = synthesize_stage1(&input).unwrap();
        let b = synthesize_stage1(&input).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn missing_readme_renders_placeholder() {
        let cfg = config_with_budget(8000);
        let files: Vec<IndexedFile> = vec![];
        let scored: Vec<ScoredSymbol> = vec![];
        let metadata = ProjectMetadata::default();
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &metadata,
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        assert!(out.contains("No README found."));
    }

    #[test]
    fn empty_files_still_renders_all_section_markers() {
        let cfg = config_with_budget(8000);
        let input = SynthesisInput {
            config: &cfg,
            files: &[],
            scored: &[],
            metadata: &ProjectMetadata::default(),
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        for marker in [
            "section=metadata",
            "section=readme",
            "section=architecture",
            "section=data_models",
            "section=end",
        ] {
            assert!(out.contains(marker), "missing marker: {marker}");
        }
        assert!(out.contains("(No data models found.)"));
    }

    #[test]
    fn key_implementations_dropped_when_over_budget() {
        // Build a file with a function whose source is gigantic.
        let big_source: String = "x".repeat(40_000);
        let body = format!("export function huge() {{\n{big_source}\n}}");
        let files = vec![mk_file(
            "src/huge.ts",
            &body,
            vec![mk_symbol("huge", SymbolKind::Function, &body)],
        )];
        let scored = crate::salience::score_all(&files);
        let cfg = config_with_budget(2000); // tiny budget
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &ProjectMetadata::default(),
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        // huge function source should not be in the output (dropped from key impls)
        assert!(!out.contains(&"x".repeat(1000)));
        // but section markers still present
        assert!(out.contains("section=end"));
    }

    #[test]
    fn essential_section_overflow_errors() {
        // Force essential sections to exceed budget by making the readme huge.
        let cfg = config_with_budget(50);
        let huge_readme = "x".repeat(10_000);
        let input = SynthesisInput {
            config: &cfg,
            files: &[],
            scored: &[],
            metadata: &ProjectMetadata::default(),
            readme_excerpt: Some(&huge_readme),
            repocontext_version: "0.2.0",
        };
        let err = synthesize_stage1(&input).expect_err("should overflow");
        let msg = format!("{err:#}");
        assert!(msg.contains("essential sections"), "got: {msg}");
        assert!(msg.contains("max_tokens"), "got: {msg}");
    }

    #[test]
    fn modules_grouped_by_module_path() {
        let cfg = config_with_budget(8000);
        let files = vec![
            mk_file(
                "src/services/auth.ts",
                "export function login() {}",
                vec![mk_symbol(
                    "login",
                    SymbolKind::Function,
                    "export function login() {}",
                )],
            ),
            mk_file(
                "src/routes/api.ts",
                "export function handle() {}",
                vec![mk_symbol(
                    "handle",
                    SymbolKind::Function,
                    "export function handle() {}",
                )],
            ),
            mk_file(
                "lib/util.ts",
                "export function util() {}",
                vec![mk_symbol(
                    "util",
                    SymbolKind::Function,
                    "export function util() {}",
                )],
            ),
        ];
        let scored = crate::salience::score_all(&files);
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &ProjectMetadata::default(),
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        // module_path takes the first 2 path components when present, so
        // src/services/auth.ts → "src/services" and lib/util.ts → "lib".
        assert!(out.contains("section=module name=\"src/services\""));
        assert!(out.contains("section=module name=\"src/routes\""));
        assert!(out.contains("section=module name=\"lib\""));
        // BTreeMap sorts alphabetically: "lib" < "src/routes" < "src/services".
        let lib_pos = out.find("section=module name=\"lib\"").unwrap();
        let routes_pos = out.find("section=module name=\"src/routes\"").unwrap();
        let services_pos = out.find("section=module name=\"src/services\"").unwrap();
        assert!(lib_pos < routes_pos);
        assert!(routes_pos < services_pos);
    }

    #[test]
    fn data_models_section_includes_interfaces_and_types() {
        let cfg = config_with_budget(8000);
        let files = vec![mk_file(
            "src/types.ts",
            "export interface User { id: string; }\nexport type Role = string;",
            vec![
                mk_symbol(
                    "User",
                    SymbolKind::Interface,
                    "export interface User { id: string; }",
                ),
                mk_symbol("Role", SymbolKind::TypeAlias, "export type Role = string;"),
            ],
        )];
        let scored = crate::salience::score_all(&files);
        let input = SynthesisInput {
            config: &cfg,
            files: &files,
            scored: &scored,
            metadata: &ProjectMetadata::default(),
            readme_excerpt: None,
            repocontext_version: "0.2.0",
        };
        let out = synthesize_stage1(&input).unwrap();
        assert!(out.contains("interface User"));
        assert!(out.contains("type Role"));
    }

    #[test]
    fn estimator_is_chars_div_4() {
        assert_eq!(estimated_tokens(""), 0);
        assert_eq!(estimated_tokens("abcd"), 1);
        assert_eq!(estimated_tokens(&"x".repeat(400)), 100);
    }
}
