//! Stitch [`EnrichResult`] chunk outputs into a polished `context.md`.
//!
//! Output structure (matches §5 of the build plan's "Stage 2: Chunking &
//! Coverage Guarantees"):
//!
//! ```text
//! # {Project Name}
//!
//! {Overview narrative — from the LLM's response to the Overview chunk}
//!
//! ## Architecture
//! {Architecture narrative}
//!
//! ## Modules
//! ### {module path 1}
//! {Module narrative — multi-part chunks concatenated by part_index}
//! ### {module path 2}
//! ...
//!
//! ## Domain Model
//! {Data models narrative}
//!
//! ## Key Behaviors
//! ### {symbol} in {file}
//! {LLM prose}
//! <fenced verbatim code block from context_temp.md>
//!
//! ---
//! *Generated by repocontext...*
//! ```
//!
//! Code blocks are copied verbatim from `context_temp.md` — the LLM never
//! reproduces code, eliminating hallucinated-code risk. The footer makes the
//! file's provenance + regeneration command discoverable.

use std::collections::BTreeMap;

use crate::orchestrator::{ChunkOutput, EnrichResult};
use crate::types::ChunkType;

/// Assemble `context.md` from chunk outputs. `project_name` is used as the
/// H1 heading; pass `None` to use a generic placeholder.
///
/// Determinism guarantee: given the same [`EnrichResult`] and `project_name`,
/// this returns byte-identical output. Multi-part module chunks are
/// concatenated by `part_index`; entries are sorted by section name.
pub fn assemble(result: &EnrichResult, project_name: Option<&str>) -> String {
    let mut out = String::new();

    let title = project_name.unwrap_or("Repository Context");
    out.push_str("# ");
    out.push_str(title);
    out.push_str("\n\n");

    // Overview narrative (no heading — sits directly under the H1).
    if let Some(overview) = find_chunk(result, ChunkType::Overview) {
        out.push_str(overview.output.trim());
        out.push_str("\n\n");
    }

    // Architecture
    if let Some(arch) = find_chunk(result, ChunkType::Architecture) {
        out.push_str("## Architecture\n\n");
        out.push_str(arch.output.trim());
        out.push_str("\n\n");
    }

    // Modules — group sub-chunks by section_name, sort alphabetically.
    let modules = collect_module_groups(result);
    if !modules.is_empty() {
        out.push_str("## Modules\n\n");
        for (section_name, parts) in &modules {
            let display = section_name.strip_prefix("module:").unwrap_or(section_name);
            out.push_str("### ");
            out.push_str(display);
            out.push_str("\n\n");
            // Concatenate parts by part_index. Single-part modules just
            // emit one piece of text.
            for part in parts {
                out.push_str(part.output.trim());
                out.push_str("\n\n");
            }
        }
    }

    // Domain Model
    if let Some(dm) = find_chunk(result, ChunkType::DataModels) {
        out.push_str("## Domain Model\n\n");
        out.push_str(dm.output.trim());
        out.push_str("\n\n");
    }

    // Key Behaviors — per-implementation prose + verbatim code block.
    let key_impls: Vec<&ChunkOutput> = result
        .chunks
        .iter()
        .filter(|c| {
            matches!(
                c.chunk.chunk_type,
                ChunkType::KeyImplementation | ChunkType::KeyImplementationElided
            )
        })
        .collect();
    if !key_impls.is_empty() {
        out.push_str("## Key Behaviors\n\n");
        for c in key_impls {
            let (heading, code_block) = split_entry(&c.chunk.content);
            out.push_str("### ");
            out.push_str(heading.trim());
            out.push_str("\n\n");
            out.push_str(c.output.trim());
            out.push_str("\n\n");
            if let Some(code) = code_block {
                out.push_str(&code);
                out.push_str("\n\n");
            }
        }
    }

    // Footer.
    out.push_str("---\n\n");
    out.push_str("*Generated by repocontext from `context_temp.md`. ");
    out.push_str("To regenerate: `repocontext generate --enrich`.*\n");

    out
}

fn find_chunk(result: &EnrichResult, kind: ChunkType) -> Option<&ChunkOutput> {
    result.chunks.iter().find(|c| c.chunk.chunk_type == kind)
}

/// Group module chunks by `section_name`, sorted alphabetically. Within each
/// group, parts are sorted by `part_index` (None treated as 0). Returns a
/// `BTreeMap` so the caller iterates in alphabetical-key order.
fn collect_module_groups(result: &EnrichResult) -> BTreeMap<String, Vec<&ChunkOutput>> {
    let mut groups: BTreeMap<String, Vec<&ChunkOutput>> = BTreeMap::new();
    for c in &result.chunks {
        if c.chunk.chunk_type == ChunkType::Module {
            groups
                .entry(c.chunk.section_name.clone())
                .or_default()
                .push(c);
        }
    }
    for parts in groups.values_mut() {
        parts.sort_by_key(|c| c.chunk.part_index.unwrap_or(0));
    }
    groups
}

/// Pull the heading text and the verbatim code block out of a key-impl entry.
/// Returns `(heading_text_without_marker, Some(code_block))` if a fenced
/// block was found. For elided entries the code block is replaced with an
/// elision marker by the chunker; we surface that marker in place of code.
fn split_entry(content: &str) -> (String, Option<String>) {
    let mut lines = content.lines();
    let first = lines.next().unwrap_or("");
    let heading = first.strip_prefix("### ").unwrap_or(first).to_string();

    // Walk the rest looking for ``` … ``` (or the elision marker line).
    let rest: Vec<&str> = lines.collect();
    if let Some((code_block, _)) = extract_code_block(&rest) {
        return (heading, Some(code_block));
    }
    if rest.iter().any(|l| l.contains("source body elided")) {
        return (
            heading,
            Some("*[source body elided — see `context_temp.md`]*".to_string()),
        );
    }
    (heading, None)
}

fn extract_code_block(lines: &[&str]) -> Option<(String, usize)> {
    let mut start: Option<usize> = None;
    for (i, line) in lines.iter().enumerate() {
        if line.starts_with("```") {
            match start {
                None => start = Some(i),
                Some(s) => {
                    let block = lines[s..=i].join("\n");
                    return Some((block, i));
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::MockBackend;
    use crate::cache::JsonFileCache;
    use crate::orchestrator::{enrich, EnrichConfig};

    const TEST_INPUT: &str = "\
<!-- repocontext:section=metadata -->
- Project: demo

<!-- repocontext:section=readme -->
A demo project.

<!-- repocontext:section=architecture -->
```
src/
  a.ts
  b.ts
```

<!-- repocontext:section=module name=\"src\" -->
### Module: src

Files: 2

#### Exports

```typescript
export function a() {}
```

<!-- repocontext:section=data_models -->
```typescript
export interface User { id: string }
```

<!-- repocontext:section=key_implementations -->
### `a` in src/a.ts

References: 1
Salience: 1.5

```typescript
export function a() {}
```

<!-- repocontext:section=end -->
";

    fn run_pipeline(input: &str) -> EnrichResult {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let cfg = EnrichConfig {
            model_id: "test-model".to_string(),
            ..EnrichConfig::default()
        };
        enrich(input, &cfg, &cache, &mut backend).unwrap()
    }

    #[test]
    fn assembled_output_includes_all_top_level_sections() {
        let result = run_pipeline(TEST_INPUT);
        let md = assemble(&result, Some("demo"));

        assert!(md.starts_with("# demo\n\n"), "got: {}", &md[..40]);
        assert!(md.contains("## Architecture"));
        assert!(md.contains("## Modules"));
        assert!(md.contains("### src"));
        assert!(md.contains("## Domain Model"));
        assert!(md.contains("## Key Behaviors"));
        assert!(md.contains("### `a` in src/a.ts"));
        assert!(md.ends_with("--enrich`.*\n"));
    }

    #[test]
    fn fallback_to_generic_title_when_no_project_name() {
        let result = run_pipeline(TEST_INPUT);
        let md = assemble(&result, None);
        assert!(md.starts_with("# Repository Context"));
    }

    #[test]
    fn key_behaviors_includes_verbatim_code_block() {
        let result = run_pipeline(TEST_INPUT);
        let md = assemble(&result, Some("demo"));

        // The code block from context_temp.md should appear verbatim.
        assert!(md.contains("```typescript\nexport function a() {}\n```"));
    }

    #[test]
    fn assembly_is_deterministic() {
        let r = run_pipeline(TEST_INPUT);
        let a = assemble(&r, Some("demo"));
        let b = assemble(&r, Some("demo"));
        assert_eq!(a, b, "assembly must be byte-deterministic");
    }

    #[test]
    fn modules_sorted_alphabetically() {
        let input = "\
<!-- repocontext:section=module name=\"zebra\" -->
content z

<!-- repocontext:section=module name=\"alpha\" -->
content a

<!-- repocontext:section=module name=\"middle\" -->
content m
";
        let r = run_pipeline(input);
        let md = assemble(&r, Some("test"));
        let alpha_pos = md.find("### alpha").unwrap();
        let middle_pos = md.find("### middle").unwrap();
        let zebra_pos = md.find("### zebra").unwrap();
        assert!(alpha_pos < middle_pos);
        assert!(middle_pos < zebra_pos);
    }

    #[test]
    fn module_subchunks_concatenate_by_part_index() {
        // Build a module big enough to force sub-splitting, then verify
        // the assembled output contains both parts under one ### heading.
        let exports = (0..15)
            .map(|i| format!("paragraph number {i} with some content"))
            .collect::<Vec<_>>()
            .join("\n\n");
        let input = format!("<!-- repocontext:section=module name=\"big\" -->\n{exports}\n");

        // Tight budget to force split.
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let cfg = EnrichConfig {
            model_id: "test-model".to_string(),
            chunker_config: crate::chunker::ChunkerConfig {
                chunk_budget_chars: 100,
                paragraphs_per_subchunk_hint: 5,
            },
            ..EnrichConfig::default()
        };
        let result = enrich(&input, &cfg, &cache, &mut backend).unwrap();

        // We expect more than one Module chunk in the result.
        let module_chunks: Vec<_> = result
            .chunks
            .iter()
            .filter(|c| c.chunk.chunk_type == ChunkType::Module)
            .collect();
        assert!(
            module_chunks.len() >= 2,
            "expected sub-split, got {} chunks",
            module_chunks.len()
        );

        let md = assemble(&result, Some("test"));

        // Only ONE `### big` heading even though there are multiple sub-chunks.
        let count = md.matches("### big").count();
        assert_eq!(count, 1, "expected one heading for `big`, got {count}");
    }

    #[test]
    fn missing_section_simply_omitted_from_output() {
        let input = "\
<!-- repocontext:section=metadata -->
- Project: demo

<!-- repocontext:section=architecture -->
```
src/
```
";
        let r = run_pipeline(input);
        let md = assemble(&r, Some("demo"));
        assert!(md.contains("## Architecture"));
        assert!(!md.contains("## Modules"));
        assert!(!md.contains("## Domain Model"));
        assert!(!md.contains("## Key Behaviors"));
    }

    #[test]
    fn elided_implementation_renders_elision_marker() {
        let huge = "x".repeat(20_000);
        let input = format!(
            "<!-- repocontext:section=key_implementations -->\n\n\
             ### `huge` in src/h.ts\n\n\
             References: 0\n\
             Salience: 1.0\n\n\
             ```typescript\n{huge}\n```\n"
        );
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let cfg = EnrichConfig {
            model_id: "test".to_string(),
            chunker_config: crate::chunker::ChunkerConfig {
                chunk_budget_chars: 500,
                paragraphs_per_subchunk_hint: 5,
            },
            ..EnrichConfig::default()
        };
        let r = enrich(&input, &cfg, &cache, &mut backend).unwrap();
        let md = assemble(&r, Some("test"));

        assert!(md.contains("### `huge` in src/h.ts"));
        assert!(md.contains("source body elided"));
        // The huge body itself should NOT appear in the assembled output.
        assert!(!md.contains(&"x".repeat(1000)));
    }

    #[test]
    fn split_entry_extracts_heading_and_code() {
        let entry = "\
### `foo` in src/foo.ts

References: 5
Salience: 3.2

```typescript
export function foo() {
  return 42;
}
```";
        let (heading, code) = split_entry(entry);
        assert_eq!(heading, "`foo` in src/foo.ts");
        let code = code.unwrap();
        assert!(code.starts_with("```typescript"));
        assert!(code.contains("export function foo()"));
        assert!(code.ends_with("```"));
    }
}
