//! Stage 2 pipeline: chunks → cache → backend → outputs.
//!
//! The orchestrator is the only piece that knows about *all* of: chunker,
//! prompt loader, cache, backend, and the failure fallback path. It exposes
//! one entry point ([`enrich`]) that the CLI calls.
//!
//! The hard guarantee from the build plan: **every input section produces an
//! output**. If the LLM fails for any reason — error, panic-caught, dry-run
//! skip — the corresponding chunk still appears in [`EnrichResult::chunks`]
//! with a placeholder output and a [`ChunkSource`] that records why.

use anyhow::{Context, Result};
use tracing::{debug, info, warn};

use crate::backend::LlmBackend;
use crate::cache::EnrichCache;
use crate::chunker::{chunk, ChunkerConfig};
use crate::prompt::PromptTemplate;
use crate::prompts::template_for;
use crate::types::{cache_key_hash, CachedEntry, Chunk, CompletionParams};

/// Standard placeholder used when a chunk fails or is skipped. Matches the
/// build plan's coverage guarantee — readers always see *something* for
/// every section, even on total backend failure.
pub const FALLBACK_PLACEHOLDER: &str =
    "*[Enrichment unavailable for this section. See context_temp.md for structural details.]*";

/// Configuration threaded through the Stage 2 pipeline.
#[derive(Debug, Clone)]
pub struct EnrichConfig {
    /// Stable identifier for the model. Participates in cache keys, so
    /// changing the model invalidates all cached outputs automatically.
    pub model_id: String,
    pub completion_params: CompletionParams,
    pub chunker_config: ChunkerConfig,
    /// `--dry-run-llm`: log rendered prompts to stderr, skip backend calls.
    pub dry_run: bool,
    /// `--no-cache`: bypass cache reads and writes for this run.
    pub no_cache: bool,
}

impl Default for EnrichConfig {
    fn default() -> Self {
        Self {
            model_id: "qwen2.5-coder-7b-instruct-q4_k_m".to_string(),
            completion_params: CompletionParams::default(),
            chunker_config: ChunkerConfig::default(),
            dry_run: false,
            no_cache: false,
        }
    }
}

/// One chunk's output plus where it came from. Returned in chunk-creation
/// order so the assembler (phase 15) can render `context.md` deterministically.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChunkOutput {
    pub chunk: Chunk,
    pub output: String,
    pub source: ChunkSource,
}

/// Where a chunk's output came from. Used for diagnostics and to drive the
/// cache-replay determinism test (which asserts `source != Llm`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChunkSource {
    /// Hit on the cache; no backend call.
    Cache,
    /// Generated by the LLM during this run.
    Llm,
    /// Backend errored; placeholder used.
    Fallback,
    /// `--dry-run-llm`; placeholder used; rendered prompt logged.
    DryRun,
}

/// Aggregate result of a Stage 2 run.
#[derive(Debug, Clone)]
pub struct EnrichResult {
    pub chunks: Vec<ChunkOutput>,
    pub cache_hits: usize,
    pub cache_misses: usize,
    pub failures: usize,
}

impl EnrichResult {
    pub fn total_chunks(&self) -> usize {
        self.chunks.len()
    }
}

/// Run the Stage 2 pipeline end-to-end. Errors only on chunker failure;
/// per-chunk LLM errors are caught, logged, and replaced with the fallback
/// placeholder.
pub fn enrich(
    context_temp: &str,
    cfg: &EnrichConfig,
    cache: &dyn EnrichCache,
    backend: &mut dyn LlmBackend,
) -> Result<EnrichResult> {
    let chunks = chunk(context_temp, &cfg.chunker_config)
        .context("splitting context_temp.md into chunks")?;

    info!("Stage 2: {} chunks to process", chunks.len());

    let mut outputs: Vec<ChunkOutput> = Vec::with_capacity(chunks.len());
    let mut cache_hits = 0usize;
    let mut cache_misses = 0usize;
    let mut failures = 0usize;

    for chunk in chunks {
        let template = match template_for(chunk.chunk_type) {
            Ok(t) => t,
            Err(e) => {
                warn!("template load failed for {:?}: {:#}", chunk.chunk_type, e);
                outputs.push(fallback_output(chunk));
                failures += 1;
                continue;
            }
        };

        let rendered = render_chunk_prompt(&template, &chunk);
        let cache_key = cache_key_hash(template.version, &cfg.model_id, &rendered);

        // Cache lookup.
        if !cfg.no_cache {
            match cache.get(&cache_key) {
                Ok(Some(entry)) => {
                    debug!(
                        "cache hit for chunk {} ({})",
                        chunk.chunk_id,
                        chunk.chunk_type.as_str()
                    );
                    outputs.push(ChunkOutput {
                        chunk,
                        output: entry.output,
                        source: ChunkSource::Cache,
                    });
                    cache_hits += 1;
                    continue;
                }
                Ok(None) => {}
                Err(e) => {
                    // A read error is non-fatal — proceed to the LLM and try
                    // to write the result back. Log so the user sees it.
                    warn!("cache read failed for {}: {:#}", chunk.chunk_id, e);
                }
            }
        }

        // --dry-run-llm short-circuits: log the rendered prompt and emit a
        // placeholder. No backend call, no cache write.
        if cfg.dry_run {
            info!(
                "--dry-run-llm: would send chunk {} ({} chars, type {})",
                chunk.chunk_id,
                rendered.len(),
                chunk.chunk_type.as_str()
            );
            println!(
                "=== chunk {} ({:?}, {} chars) ===\n{}\n",
                chunk.chunk_id,
                chunk.chunk_type,
                rendered.len(),
                rendered
            );
            outputs.push(ChunkOutput {
                chunk,
                output: "[dry run — prompt logged to stdout]".to_string(),
                source: ChunkSource::DryRun,
            });
            continue;
        }

        // Real backend call.
        cache_misses += 1;
        match backend.complete("", &rendered, &cfg.completion_params) {
            Ok(response) => {
                let trimmed = response.trim().to_string();
                if !cfg.no_cache {
                    let entry = CachedEntry {
                        chunk_type: chunk.chunk_type,
                        section_name: chunk.section_name.clone(),
                        input_preview: rendered.chars().take(120).collect(),
                        output: trimmed.clone(),
                        prompt_version: template.version,
                        model_id: cfg.model_id.clone(),
                    };
                    if let Err(e) = cache.put(&cache_key, entry) {
                        warn!("cache put failed for {}: {:#}", chunk.chunk_id, e);
                    }
                }
                outputs.push(ChunkOutput {
                    chunk,
                    output: trimmed,
                    source: ChunkSource::Llm,
                });
            }
            Err(e) => {
                warn!(
                    "LLM call failed for chunk {} ({}): {:#}",
                    chunk.chunk_id,
                    chunk.chunk_type.as_str(),
                    e
                );
                outputs.push(fallback_output(chunk));
                failures += 1;
            }
        }
    }

    // Persist any new cache writes from this run.
    if !cfg.no_cache && !cfg.dry_run {
        if let Err(e) = cache.flush() {
            warn!("cache flush failed: {:#}", e);
        }
    }

    info!(
        "Stage 2 done: {} chunks ({} cache hits, {} LLM calls, {} failures)",
        outputs.len(),
        cache_hits,
        cache_misses - failures,
        failures
    );

    Ok(EnrichResult {
        chunks: outputs,
        cache_hits,
        cache_misses,
        failures,
    })
}

fn fallback_output(chunk: Chunk) -> ChunkOutput {
    ChunkOutput {
        chunk,
        output: FALLBACK_PLACEHOLDER.to_string(),
        source: ChunkSource::Fallback,
    }
}

fn render_chunk_prompt(template: &PromptTemplate, chunk: &Chunk) -> String {
    let cross_refs = if chunk.cross_references.is_empty() {
        "(none)".to_string()
    } else {
        chunk.cross_references.join(", ")
    };
    template.render(&[
        ("section_name", chunk.section_name.as_str()),
        ("cross_references", cross_refs.as_str()),
        ("content", chunk.content.as_str()),
    ])
}

/// Stub assembler used until phase 15 ships the real one. Concatenates chunk
/// outputs in order with section headings — structurally complete but visually
/// rough. Phase 15 replaces this with a polished `context.md` layout.
pub fn assemble_basic(result: &EnrichResult) -> String {
    let mut out = String::new();
    out.push_str("# Repository Context\n\n");
    out.push_str(&format!(
        "<!-- Stage 2 enrichment: {} chunks ({} cache, {} LLM, {} fallback). \
         Phase 15 will replace this stub assembly with a polished layout. -->\n\n",
        result.chunks.len(),
        result.cache_hits,
        result.cache_misses - result.failures,
        result.failures,
    ));

    for output in &result.chunks {
        out.push_str(&format!(
            "## {} ({})\n\n",
            output.chunk.section_name,
            output.chunk.chunk_type.as_str()
        ));
        out.push_str(&output.output);
        out.push_str("\n\n");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::{FailBackend, MockBackend, PanicBackend};
    use crate::cache::JsonFileCache;

    /// Minimal context_temp.md covering every section type — used by most tests.
    const TEST_INPUT: &str = "\
<!-- repocontext:section=metadata -->
- Project: demo

<!-- repocontext:section=readme -->
A demo.

<!-- repocontext:section=architecture -->
```
src/
```

<!-- repocontext:section=module name=\"src\" -->
content for src module

<!-- repocontext:section=data_models -->
```typescript
export interface Foo {}
```

<!-- repocontext:section=key_implementations -->
### `foo` in src/foo.ts

```typescript
export function foo() {}
```

<!-- repocontext:section=end -->
";

    fn cfg() -> EnrichConfig {
        EnrichConfig {
            model_id: "test-model".to_string(),
            ..EnrichConfig::default()
        }
    }

    #[test]
    fn mock_backend_produces_outputs_for_every_chunk() {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let result = enrich(TEST_INPUT, &cfg(), &cache, &mut backend).unwrap();

        // 5 chunk types: Overview (metadata+readme), Architecture, Module, DataModels, KeyImplementation
        assert_eq!(result.chunks.len(), 5);
        for output in &result.chunks {
            assert!(!output.output.is_empty());
            assert!(output.output.starts_with("[Mock summary"));
            assert_eq!(output.source, ChunkSource::Llm);
        }
        assert_eq!(result.cache_hits, 0);
        assert_eq!(result.cache_misses, 5);
        assert_eq!(result.failures, 0);
    }

    #[test]
    fn second_run_with_populated_cache_uses_cache() {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let _r1 = enrich(TEST_INPUT, &cfg(), &cache, &mut backend).unwrap();

        // Second run: PanicBackend would panic if called, proving the cache served everything.
        let mut panic_backend = PanicBackend;
        let r2 = enrich(TEST_INPUT, &cfg(), &cache, &mut panic_backend).unwrap();
        assert_eq!(r2.cache_hits, 5);
        assert_eq!(r2.cache_misses, 0);
        for output in &r2.chunks {
            assert_eq!(output.source, ChunkSource::Cache);
        }
    }

    #[test]
    fn fail_backend_produces_placeholder_for_every_chunk() {
        let cache = JsonFileCache::in_memory();
        let mut backend = FailBackend;
        let result = enrich(TEST_INPUT, &cfg(), &cache, &mut backend).unwrap();

        // Every chunk failed; every chunk still has a placeholder output.
        // This is the coverage guarantee.
        assert_eq!(result.chunks.len(), 5);
        for output in &result.chunks {
            assert_eq!(output.source, ChunkSource::Fallback);
            assert!(output.output.contains("Enrichment unavailable"));
        }
        assert_eq!(result.failures, 5);
    }

    #[test]
    fn no_cache_flag_bypasses_reads_and_writes() {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let mut cfg_no_cache = cfg();
        cfg_no_cache.no_cache = true;

        // First run: cache should not be populated even though backend was called.
        let r1 = enrich(TEST_INPUT, &cfg_no_cache, &cache, &mut backend).unwrap();
        assert_eq!(r1.cache_hits, 0);
        assert!(cache.is_empty(), "no-cache run should leave cache empty");

        // Second run: still hits the backend, no cache hits.
        let r2 = enrich(TEST_INPUT, &cfg_no_cache, &cache, &mut backend).unwrap();
        assert_eq!(r2.cache_hits, 0);
        assert_eq!(r2.cache_misses, 5);
    }

    #[test]
    fn dry_run_does_not_call_backend() {
        let cache = JsonFileCache::in_memory();
        // PanicBackend would panic if --dry-run-llm let any call through.
        let mut backend = PanicBackend;
        let mut cfg_dry = cfg();
        cfg_dry.dry_run = true;

        let result = enrich(TEST_INPUT, &cfg_dry, &cache, &mut backend).unwrap();
        for output in &result.chunks {
            assert_eq!(output.source, ChunkSource::DryRun);
            assert!(output.output.contains("dry run"));
        }
    }

    #[test]
    fn cache_key_includes_model_id() {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let cfg_a = EnrichConfig {
            model_id: "model-a".to_string(),
            ..EnrichConfig::default()
        };
        let cfg_b = EnrichConfig {
            model_id: "model-b".to_string(),
            ..EnrichConfig::default()
        };

        // Populate cache with model-a outputs
        let _ = enrich(TEST_INPUT, &cfg_a, &cache, &mut backend).unwrap();

        // Run with model-b: keys differ, so all cache misses
        let r2 = enrich(TEST_INPUT, &cfg_b, &cache, &mut backend).unwrap();
        assert_eq!(r2.cache_hits, 0);
        assert_eq!(r2.cache_misses, 5);
    }

    #[test]
    fn assemble_basic_includes_every_chunk() {
        let cache = JsonFileCache::in_memory();
        let mut backend = MockBackend;
        let result = enrich(TEST_INPUT, &cfg(), &cache, &mut backend).unwrap();
        let assembled = assemble_basic(&result);

        for output in &result.chunks {
            assert!(
                assembled.contains(&output.chunk.section_name),
                "section {} missing from assembled output",
                output.chunk.section_name
            );
        }
        assert!(assembled.starts_with("# Repository Context"));
    }

    #[test]
    fn coverage_under_total_failure() {
        // The HARD guarantee: every section in the input has an output, even
        // when the backend fails on every call.
        let input = TEST_INPUT;
        let cache = JsonFileCache::in_memory();
        let mut backend = FailBackend;
        let result = enrich(input, &cfg(), &cache, &mut backend).unwrap();

        // Count input section markers
        let input_section_count = input.matches("<!-- repocontext:section=").count() - 1; // minus "end"
                                                                                          // Each input section produces ≥1 output chunk (some metadata/readme combine into Overview).
                                                                                          // Specifically: metadata+readme → Overview (1), architecture (1), module (1), data_models (1), key_impls (1)
                                                                                          // So 6 input markers (incl. end) → 5 chunks.
        assert_eq!(result.chunks.len(), 5);
        assert_eq!(input_section_count, 6); // metadata, readme, architecture, module, data_models, key_implementations

        // Every chunk has output text (even if it's the fallback placeholder).
        for output in &result.chunks {
            assert!(!output.output.is_empty());
        }
    }
}
